"""Defines the Maven artifacts which are fetched and checked into source."""

# keep sorted
ARTIFACTS = [
    "androidx.annotation:annotation:1.1.0",
    "androidx.annotation:annotation-jvm:1.7.1",
    "androidx.lint:lint-gradle:1.0.0-alpha01",
    "com.android.tools.build:bundletool:1.17.1",
    "com.android.tools.build.jetifier:jetifier-core:1.0.0-beta10",
    "com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta10",
    "com.android.tools.build:transform-api:2.0.0-deprecated-use-gradle-api",
    "com.android.tools:desugar_jdk_libs:1.1.5",
    "com.android.tools:desugar_jdk_libs_configuration:1.1.5",
    "com.android.tools:desugar_jdk_libs_configuration_nio:2.0.2",
    "com.android.tools:desugar_jdk_libs_nio:2.0.2",
    "com.android.tools:r8:8.2.47",
    "com.android.tools.smali:smali-baksmali:3.0.3",
    "com.android.tools.smali:smali-dexlib2:3.0.3",
    "com.fasterxml:aalto-xml:1.3.0",
    "com.fasterxml.jackson.core:jackson-annotations:2.11.1",
    "com.fasterxml.jackson.core:jackson-core:2.11.1",
    "com.fasterxml.jackson.core:jackson-databind:2.11.1",
    "com.github.javaparser:javaparser-core:3.23.0",
    "com.github.rising3:semver:0.3.1",
    "com.google.api-client:google-api-client:1.35.2",
    "com.google.apis:google-api-services-cloudbilling:v1-rev20240119-2.0.0",
    "com.google.apis:google-api-services-cloudresourcemanager:v3-rev20230416-2.0.0",
    "com.google.apis:google-api-services-monitoring:v3-rev20230806-2.0.0",
    "com.google.apis:google-api-services-oauth2:v2-rev20200213-2.0.0",
    "com.google.apis:google-api-services-sourcerepo:v1-rev20230123-2.0.0",
    "com.google.apis:google-api-services-storage:v1-rev20230301-2.0.0",
    "com.google.apis:google-api-services-testing:v1-rev20240213-2.0.0",
    "com.google.apis:google-api-services-toolresults:v1beta3-rev20230410-2.0.0",
    "com.google.auto:auto-common:0.10",
    "com.google.auto.value:auto-value:1.10.1",
    "com.google.auto.value:auto-value-annotations:1.10.1",
    "com.google.code.findbugs:jsr305:3.0.2",
    "com.google.code.gson:gson:2.10.1",
    "com.google.crypto.tink:tink:1.7.0",
    "com.google.errorprone:error_prone_annotations:2.28.0",
    "com.google.flatbuffers:flatbuffers-java:1.12.0",
    "com.google.flogger:flogger:0.8",
    "com.google.flogger:flogger-system-backend:0.8",
    "com.google.guava:guava:32.0.1-jre",
    "com.google.guava:guava-testlib:32.0.1-jre",
    "com.google.http-client:google-http-client:1.43.3",
    "com.google.http-client:google-http-client-apache-v2:1.42.0",
    "com.google.http-client:google-http-client-gson:1.43.3",
    "com.google.http-client:google-http-client-jackson2:1.22.0",
    "com.google.jimfs:jimfs:1.1",
    "com.google.oauth-client:google-oauth-client:1.35.0",
    "com.google.oauth-client:google-oauth-client-java6:1.35.0",
    "com.google.protobuf:protobuf-bom:pom:3.22.3",
    "com.google.protobuf:protobuf-gradle-plugin:0.9.3",
    "com.google.protobuf:protobuf-java:3.22.3",
    "com.google.protobuf:protobuf-java-util:3.22.3",
    "com.google.protobuf:protobuf-parent:pom:3.22.3",
    "com.google.protobuf:protoc:exe:linux-x86_64:3.22.3",
    "com.google.protobuf:protoc:exe:osx-aarch_64:3.22.3",
    "com.google.protobuf:protoc:exe:osx-x86_64:3.22.3",
    "com.google.protobuf:protoc:exe:windows-x86_64:3.22.3",
    "com.google.re2j:re2j:1.7",
    "com.google.testing.compile:compile-testing:0.16",
    "com.google.testing.platform:android-device-provider-local:0.0.9-alpha02",
    "com.google.testing.platform:android-driver-instrumentation:0.0.9-alpha02",
    "com.google.testing.platform:android-test-plugin:0.0.9-alpha02",
    "com.google.testing.platform:core:0.0.9-alpha02",
    "com.google.testing.platform:core-proto:0.0.9-alpha02",
    "com.google.testing.platform:launcher:0.0.9-alpha02",
    "com.google.truth.extensions:truth-java8-extension:0.44",
    "com.google.truth:truth:0.44",
    "com.googlecode.jarjar:jarjar:1.3",
    "com.googlecode.juniversalchardet:juniversalchardet:1.0.3",
    "com.nothome:javaxdelta:2.0.1",
    "com.squareup:javapoet:1.10.0",
    "com.squareup:javawriter:2.5.0",
    "com.squareup.okhttp:okhttp:2.5.0",
    "com.squareup.okhttp3:mockwebserver:4.12.0",
    "com.squareup.okhttp3:okhttp:4.12.0",
    "com.squareup.okio:okio:1.15.0",
    "com.squareup.okio:okio-jvm:3.0.0",
    "com.sun.activation:javax.activation:1.2.0",
    "commons-cli:commons-cli:1.4",
    "commons-codec:commons-codec:1.10",
    "commons-io:commons-io:2.13.0",
    "commons-lang:commons-lang:2.6",
    "commons-logging:commons-logging:1.2",
    "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext:0.8.1",
    "io.grpc:grpc-all:1.57.0",
    "io.grpc:grpc-api:1.57.0",
    "io.grpc:grpc-auth:1.57.0",
    "io.grpc:grpc-context:1.57.0",
    "io.grpc:grpc-core:1.57.0",
    "io.grpc:grpc-netty:1.57.0",
    "io.grpc:grpc-netty-shaded:1.57.0",
    "io.grpc:grpc-okhttp:1.57.0",
    "io.grpc:grpc-protobuf:1.57.0",
    "io.grpc:grpc-protobuf-lite:1.57.0",
    "io.grpc:grpc-stub:1.57.0",
    "io.grpc:protoc-gen-grpc-java:exe:linux-x86_64:1.57.0",
    "io.grpc:protoc-gen-grpc-java:exe:osx-aarch_64:1.57.0",
    "io.grpc:protoc-gen-grpc-java:exe:osx-x86_64:1.57.0",
    "io.grpc:protoc-gen-grpc-java:exe:windows-x86_64:1.57.0",
    "io.netty:netty-all:4.1.93.Final",
    "io.netty:netty-buffer:4.1.93.Final",
    "io.netty:netty-codec:4.1.93.Final",
    "io.netty:netty-codec-http:4.1.93.Final",
    "io.netty:netty-codec-http2:4.1.93.Final",
    "io.netty:netty-codec-socks:4.1.93.Final",
    "io.netty:netty-common:4.1.93.Final",
    "io.netty:netty-handler:4.1.93.Final",
    "io.netty:netty-handler-proxy:4.1.93.Final",
    "io.netty:netty-resolver:4.1.93.Final",
    "io.netty:netty-transport:4.1.93.Final",
    "io.opencensus:opencensus-api:0.21.0",
    "io.opencensus:opencensus-contrib-grpc-metrics:0.21.0",
    "io.perfmark:perfmark-api:0.17.0",
    "it.unimi.dsi:fastutil:8.4.0",
    "jakarta.xml.bind:jakarta.xml.bind-api:2.3.2",
    "javax.annotation:javax.annotation-api:1.3.2",
    "javax.inject:javax.inject:1",
    "javax.servlet:javax.servlet-api:3.0.1",
    "javax.xml.bind:jaxb-api:2.3.1",
    "junit:junit:4.13.2",
    "log4j:log4j:1.2.17",
    "net.java.dev.jna:jna:5.6.0",
    "net.java.dev.jna:jna-platform:5.6.0",
    "net.sf.jopt-simple:jopt-simple:4.9",
    "net.sf.kxml:kxml2:2.3.0",
    "net.sf.proguard:proguard-gradle:5.2.1",
    "nl.jqno.equalsverifier:equalsverifier:3.15.6",
    "org.apache.bcel:bcel:6.9.0",
    "org.apache.commons:commons-compress:1.21",
    "org.apache.httpcomponents:httpclient:4.5.6",
    "org.apache.httpcomponents:httpcore:4.4.10",
    "org.apache.httpcomponents:httpmime:4.5.6",
    "org.apache.maven:maven-aether-provider:3.3.9",
    "org.apache.maven:maven-model-builder:3.9.1",
    "org.bouncycastle:bcpkix-jdk18on:1.77",
    "org.bouncycastle:bcprov-jdk18on:1.77",
    "org.bytedeco:ffmpeg:6.0-1.5.9",
    "org.codehaus.groovy:groovy-all:pom:3.0.22",
    "org.commonmark:commonmark:0.22.0",
    "org.eclipse.aether:aether-connector-basic:1.0.2.v20150114",
    "org.eclipse.aether:aether-transport-file:1.0.2.v20150114",
    "org.eclipse.aether:aether-transport-http:1.0.2.v20150114",
    "org.eclipse.elk:org.eclipse.elk.alg.layered:0.3.0",
    "org.eclipse.elk:org.eclipse.elk.core:0.3.0",
    "org.eclipse.elk:org.eclipse.elk.graph:0.3.0",
    "org.eclipse.emf:org.eclipse.emf.common:2.12.0",
    "org.eclipse.emf:org.eclipse.emf.ecore:2.12.0",
    "org.glassfish.jaxb:jaxb-runtime:2.3.2",
    "org.glassfish.jaxb:jaxb-xjc:2.3.2",
    "org.gradle:gradle-tooling-api:8.10.2",
    "org.hamcrest:hamcrest-core:1.3",
    "org.hamcrest:hamcrest-library:1.3",
    "org.hdrhistogram:HdrHistogram:2.1.12",
    "org.jacoco:org.jacoco.agent:0.8.12",
    "org.jacoco:org.jacoco.build:pom:0.8.12",
    "org.jacoco:org.jacoco.core:0.8.12",
    "org.jacoco:org.jacoco.report:0.8.12",
    "org.jetbrains.dokka:dokka-core:1.4.32",
    "org.jetbrains.intellij.deps:asm-all:8.0.1",
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:1.9.20",
    "org.jetbrains.kotlin:kotlin-compiler:1.9.20",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.9.20",
    "org.jetbrains.kotlin:kotlin-reflect:1.9.20",
    "org.jetbrains.kotlin:kotlin-stdlib-common:1.9.20",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.20",
    "org.jetbrains.kotlin:kotlin-test:1.9.20",
    "org.jetbrains.kotlin:kotlin-test-junit:1.9.20",
    "org.jetbrains.kotlinx:kotlinx-cli-jvm:0.3.1",
    "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.1",
    "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4",
    "org.jetbrains.kotlinx:kotlinx-coroutines-guava:1.6.4",
    "org.jetbrains.kotlinx:kotlinx-coroutines-test-jvm:1.6.4",
    "org.jetbrains:markdown:pom:0.2.1",
    "org.jspecify:jspecify:0.2.0",
    "org.mockito:mockito-core:5.12.0",
    "org.mortbay.jetty:jetty:6.1.26",
    "org.ow2.asm:asm:9.7",
    "org.ow2.asm:asm-analysis:9.7",
    "org.ow2.asm:asm-bom:pom:9.7",
    "org.ow2.asm:asm-commons:9.7",
    "org.ow2.asm:asm-tree:9.7",
    "org.ow2.asm:asm-util:9.7",
    "org.robolectric:android-all-instrumented:9-robolectric-4913185-2-i4",
    "org.robolectric:robolectric:4.8.2",
    "org.slf4j:slf4j-simple:1.7.2",
    "org.tensorflow:tensorflow-lite-metadata:0.1.0-rc2",
    "org.tomlj:tomlj:1.1.0",
    "org.xerial:sqlite-jdbc:3.43.0.0",
]

DATA = [
    # Class JARs
    # keep sorted
    "android.arch.core:common:1.1.1",
    "android.arch.core:runtime:1.1.1",
    "android.arch.lifecycle:common:1.0.3",
    "android.arch.lifecycle:common:1.1.1",
    "android.arch.lifecycle:compiler:1.0.0",
    "android.arch.lifecycle:extensions:1.0.0",
    "android.arch.lifecycle:livedata:1.1.1",
    "android.arch.lifecycle:livedata-core:1.1.1",
    "android.arch.lifecycle:runtime:1.0.3",
    "android.arch.lifecycle:runtime:1.1.1",
    "android.arch.lifecycle:viewmodel:1.1.1",
    "android.arch.navigation:navigation-common:1.0.0",
    "android.arch.navigation:navigation-fragment:1.0.0",
    "android.arch.navigation:navigation-ui:1.0.0",
    "android.arch.persistence.room:runtime:1.0.0",
    "androidx.activity:activity-compose:1.5.1",  # Still needed from //tools/base/build-system/integration-tests
    "androidx.activity:activity-compose:1.6.1",  # Dependency of architecture-samples
    "androidx.activity:activity-compose:1.7.2",  # Still needed from //tools/base/android-templates/BUILD
    "androidx.activity:activity-compose:1.8.0",
    "androidx.activity:activity-ktx:1.4.0",
    "androidx.activity:activity-ktx:1.6.0",  # Still needed from navigation-fragment-ktx:2.5.3
    "androidx.activity:activity-ktx:1.7.0",
    "androidx.activity:activity-ktx:1.8.0",
    "androidx.annotation:annotation:1.2.0",
    "androidx.annotation:annotation:1.2.0-beta01",
    "androidx.annotation:annotation:1.6.0",
    "androidx.annotation:annotation-jvm:1.6.0",
    "androidx.appcompat:appcompat:1.0.2",
    "androidx.appcompat:appcompat:1.3.0",
    "androidx.appcompat:appcompat:1.3.0-beta01",
    "androidx.appcompat:appcompat:1.4.1",
    "androidx.appcompat:appcompat:1.6.1",
    "androidx.arch.core:core-testing:2.1.0",  # Dependency of architecture-samples
    "androidx.benchmark:benchmark-baseline-profile-gradle-plugin:1.2.4",
    "androidx.benchmark:benchmark-gradle-plugin:1.2.4",
    "androidx.cardview:cardview:1.0.0",
    "androidx.collection:collection:1.4.0",
    "androidx.collection:collection-ktx:1.4.0",  # Compose BOM 2024.04.01
    "androidx.compose.animation:animation:1.3.0",
    "androidx.compose.animation:animation:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.animation:animation:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.animation:animation:1.7.0-beta05",
    "androidx.compose.animation:animation-android:1.8.0-alpha03",  # Compose Desktop Lint checks
    "androidx.compose.animation:animation-core:1.3.3",  # Dependency of architecture-samples
    "androidx.compose.animation:animation-core-android:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.animation:animation-core-android:1.8.0-alpha03",  # Compose Desktop Lint checks
    "androidx.compose.compiler:compiler:1.2.0",
    "androidx.compose.compiler:compiler:1.3.2",
    "androidx.compose.compiler:compiler:1.4.3",  # Dependency of architecture-samples
    "androidx.compose.compiler:compiler:1.4.7",
    "androidx.compose.compiler:compiler:1.5.1",
    "androidx.compose.compiler:compiler:1.5.11",
    "androidx.compose:compose-bom:pom:2022.10.00",
    "androidx.compose:compose-bom:pom:2023.01.00",  # Dependency of architecture-samples
    "androidx.compose:compose-bom:pom:2023.03.00",
    "androidx.compose:compose-bom:pom:2023.06.00",
    "androidx.compose:compose-bom:pom:2024.04.01",
    "androidx.compose.foundation:foundation:1.3.0",
    "androidx.compose.foundation:foundation:1.3.1",  # Dependency of architecture-samples
    "androidx.compose.foundation:foundation:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.foundation:foundation:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.foundation:foundation-android:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.foundation:foundation-android:1.8.0-alpha03",  # Compose Desktop Lint checks
    "androidx.compose.foundation:foundation-layout:1.3.1",  # Dependency of architecture-samples
    "androidx.compose.foundation:foundation-layout:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.material:material:1.3.0",  # Needed by //tools/base/build-system/integration-test/...
    "androidx.compose.material:material:1.4.3",  # Necessary for Compose for TV.
    "androidx.compose.material:material:1.5.0-alpha04",
    "androidx.compose.material:material:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.material:material-android:1.8.0-alpha03",  # Compose Desktop Lint checks
    "androidx.compose.material:material-icons-core:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.material:material-icons-extended:1.3.0",
    "androidx.compose.material:material-ripple:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.material3:material3:1.0.0",
    "androidx.compose.material3:material3:1.1.1",
    "androidx.compose.material3:material3:1.2.1",  # Compose BOM 2024.04.01
    "androidx.compose.material3:material3-android:1.3.0",  # Compose Desktop Lint checks
    "androidx.compose.runtime:runtime:1.3.3",  # Dependency of architecture-samples
    "androidx.compose.runtime:runtime:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.runtime:runtime-android:1.8.0-alpha03",  # Compose Desktop Lint checks
    "androidx.compose.runtime:runtime-livedata:1.3.0",
    "androidx.compose.runtime:runtime-saveable:1.3.3",  # Dependency of architecture-samples
    "androidx.compose.runtime:runtime-saveable:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.runtime:runtime-saveable-android:1.8.0-alpha03",  # Compose Desktop Lint checks
    "androidx.compose.ui:ui:1.3.0",
    "androidx.compose.ui:ui:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.ui:ui:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.ui:ui-android:1.8.0-alpha03",  # Compose Desktop Lint checks
    "androidx.compose.ui:ui-graphics:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.ui:ui-graphics-android:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.ui:ui-graphics-android:1.8.0-alpha03",  # Compose Desktop Lint checks
    "androidx.compose.ui:ui-test-android:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.ui:ui-test-junit4:1.2.0",
    "androidx.compose.ui:ui-test-junit4:1.3.0",
    "androidx.compose.ui:ui-test-junit4:1.3.3",  # Dependency of architecture-samples
    "androidx.compose.ui:ui-test-junit4:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.ui:ui-test-junit4:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.ui:ui-test-junit4:1.7.0-beta03",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.compose.ui:ui-test-junit4:1.7.0-beta05",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.compose.ui:ui-test-junit4-android:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.ui:ui-test-manifest:1.3.0",
    "androidx.compose.ui:ui-test-manifest:1.3.3",  # Dependency of architecture-samples
    "androidx.compose.ui:ui-test-manifest:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.ui:ui-test-manifest:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.ui:ui-test-manifest:1.7.0-beta03",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.compose.ui:ui-test-manifest:1.7.0-beta05",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.compose.ui:ui-test-manifest:1.8.0-alpha03",  # Compose Desktop Lint checks
    "androidx.compose.ui:ui-text:1.3.3",  # Dependency of architecture-samples
    "androidx.compose.ui:ui-text-android:1.8.0-alpha03",  # Compose Desktop Lint checks
    "androidx.compose.ui:ui-tooling:1.2.0",  # Still needed from //tools/data-binding/compilationTests
    "androidx.compose.ui:ui-tooling:1.3.0",  # Still needed from //tools/base/build-system/integration-tests
    "androidx.compose.ui:ui-tooling:1.3.3",  # Dependency of architecture-samples
    "androidx.compose.ui:ui-tooling:1.4.3",  # Still needed from //tools/adt/idea/integration:BuildAndRunKMPTest
    "androidx.compose.ui:ui-tooling:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.ui:ui-tooling:1.6.5",
    "androidx.compose.ui:ui-tooling:1.6.6",  # Compose BOM 2024.04.01
    "androidx.compose.ui:ui-tooling:1.7.0-beta03",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.compose.ui:ui-tooling:1.7.0-beta05",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.compose.ui:ui-tooling-android:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.ui:ui-tooling-data-android:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.ui:ui-tooling-preview:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.ui:ui-tooling-preview:1.6.5",
    "androidx.compose.ui:ui-tooling-preview-android:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.ui:ui-unit-android:1.5.0-beta01",  # Necessary for Compose for TV.
    "androidx.compose.ui:ui-util:1.3.3",  # Dependency of architecture-samples
    "androidx.concurrent:concurrent-futures-ktx:1.2.0",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.constraintlayout:constraintlayout:1.1.3",
    "androidx.constraintlayout:constraintlayout:2.1.3",
    "androidx.constraintlayout:constraintlayout:2.1.4",
    "androidx.core:core:1.5.0-beta01",
    "androidx.core:core:1.5.0-rc02",
    "androidx.core:core-ktx:1.0.1",
    "androidx.core:core-ktx:1.0.2",
    "androidx.core:core-ktx:1.10.0",
    "androidx.core:core-ktx:1.10.1",
    "androidx.core:core-ktx:1.11.0-alpha04",
    "androidx.core:core-ktx:1.11.0-beta01",  # Necessary for Compose for TV.
    "androidx.core:core-ktx:1.12.0",
    "androidx.core:core-ktx:1.12.0-alpha05",
    "androidx.core:core-ktx:1.13.0",
    "androidx.core:core-ktx:1.13.1",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.core:core-ktx:1.2.0",
    "androidx.core:core-ktx:1.3.0",
    "androidx.core:core-ktx:1.3.2",
    "androidx.core:core-ktx:1.6.0",
    "androidx.core:core-ktx:1.8.0",
    "androidx.core:core-ktx:1.9.0",
    "androidx.core:core-splashscreen:1.0.1",
    "androidx.customview:customview-poolingcontainer:1.0.0-beta01",
    "androidx.databinding:databinding-adapters:8.5.0",
    "androidx.databinding:databinding-common:8.5.0",
    "androidx.databinding:databinding-compiler:8.5.0",
    "androidx.databinding:databinding-ktx:8.5.0",
    "androidx.databinding:databinding-runtime:8.5.0",
    "androidx.databinding:viewbinding:7.2.0",
    "androidx.databinding:viewbinding:7.4.1",
    "androidx.databinding:viewbinding:8.0.0-beta04",
    "androidx.datastore:datastore-core-android:1.1.0-alpha04",
    "androidx.datastore:datastore-core-okio-jvm:1.1.0-alpha04",
    "androidx.datastore:datastore-preferences-core:1.1.0-alpha04",
    "androidx.datastore:datastore-preferences-core-jvm:1.1.0-alpha04",
    "androidx.documentfile:documentfile:1.0.1",
    "androidx.emoji2:emoji2-views-helper:1.3.0",
    "androidx.emoji2:emoji2-views-helper:1.4.0",
    "androidx.emoji2:emoji2-views-helper:1.4.0-beta03",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.emoji2:emoji2-views-helper:1.4.0-beta04",  # Necessary for Compose for TV.
    "androidx.fragment:fragment:1.3.0",
    "androidx.fragment:fragment:1.3.0-rc01",
    "androidx.fragment:fragment-ktx:1.5.6",
    "androidx.games:games-activity:1.2.2",
    "androidx.leanback:leanback:1.0.0",
    "androidx.legacy:legacy-support-v13:1.0.0",
    "androidx.legacy:legacy-support-v4:1.0.0",
    "androidx.lifecycle:lifecycle-common-java8:2.4.0",
    "androidx.lifecycle:lifecycle-common-java8:2.6.1",
    "androidx.lifecycle:lifecycle-common-java8:2.6.2",
    "androidx.lifecycle:lifecycle-extensions:2.2.0",
    "androidx.lifecycle:lifecycle-livedata:2.6.0-alpha03",  # Dependency of architecture-samples
    "androidx.lifecycle:lifecycle-livedata:2.8.3",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.lifecycle:lifecycle-livedata-core-ktx:2.6.2",
    "androidx.lifecycle:lifecycle-livedata-ktx:2.2.0",
    "androidx.lifecycle:lifecycle-livedata-ktx:2.3.1",
    "androidx.lifecycle:lifecycle-livedata-ktx:2.4.0",  # Needed for tools/data-binding:runtimeLibrariesAndroidX
    "androidx.lifecycle:lifecycle-livedata-ktx:2.4.1",
    "androidx.lifecycle:lifecycle-livedata-ktx:2.6.1",
    "androidx.lifecycle:lifecycle-livedata-ktx:2.6.2",
    "androidx.lifecycle:lifecycle-livedata-ktx:2.8.3",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.lifecycle:lifecycle-process:2.4.0",  # Needed for tools/data-binding:runtimeLibrariesAndroidX
    "androidx.lifecycle:lifecycle-process:2.6.1",
    "androidx.lifecycle:lifecycle-process:2.6.2",
    "androidx.lifecycle:lifecycle-process:2.8.3",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.lifecycle:lifecycle-reactivestreams:2.6.2",
    "androidx.lifecycle:lifecycle-runtime:2.4.0",  # Needed for tools/data-binding:runtimeLibrariesAndroidX
    "androidx.lifecycle:lifecycle-runtime:2.6.1",
    "androidx.lifecycle:lifecycle-runtime:2.8.0-alpha02",  # Needed for kmp consumption test
    "androidx.lifecycle:lifecycle-runtime-android:2.8.0-alpha02",  # Needed for kmp consumption test
    "androidx.lifecycle:lifecycle-runtime-compose:2.6.0-alpha03",  # Dependency of architecture-samples
    "androidx.lifecycle:lifecycle-runtime-compose:2.6.1",
    "androidx.lifecycle:lifecycle-runtime-compose:2.8.3",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.lifecycle:lifecycle-runtime-desktop:2.8.0-alpha02",  # Needed for kmp consumption test
    "androidx.lifecycle:lifecycle-runtime-ktx:2.4.0",  # Needed for tools/data-binding:runtimeLibrariesAndroidX
    "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1",
    "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2",
    "androidx.lifecycle:lifecycle-runtime-testing:2.6.0-alpha03",  # Dependency of architecture-samples
    "androidx.lifecycle:lifecycle-service:2.4.0",  # Needed for tools/data-binding:runtimeLibrariesAndroidX
    "androidx.lifecycle:lifecycle-service:2.6.1",
    "androidx.lifecycle:lifecycle-service:2.6.2",
    "androidx.lifecycle:lifecycle-viewmodel:2.6.2",
    "androidx.lifecycle:lifecycle-viewmodel:2.8.3",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.lifecycle:lifecycle-viewmodel-compose:2.6.0-alpha03",  # Dependency of architecture-samples
    "androidx.lifecycle:lifecycle-viewmodel-compose:2.6.1",
    "androidx.lifecycle:lifecycle-viewmodel-compose:2.8.3",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1",  # Needed for AndroidTestRunConfigurationTest#testCanRunLibTestsInDebugBuildWithNoAndroidManifest
    "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0",  # Needed for tools/data-binding:runtimeLibrariesAndroidX
    "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.1",
    "androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1",
    "androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.2",
    "androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.3",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.1",
    "androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.2",
    "androidx.media:media:1.5.0",
    "androidx.media:media:1.6.0",
    "androidx.multidex:multidex:2.0.0",
    "androidx.multidex:multidex:2.0.1",
    "androidx.multidex:multidex-instrumentation:2.0.0",
    "androidx.navigation:navigation-compose:2.5.3",  # Dependency of architecture-samples
    "androidx.navigation:navigation-fragment:2.0.0",
    "androidx.navigation:navigation-fragment:2.5.2",
    "androidx.navigation:navigation-fragment:2.5.3",
    "androidx.navigation:navigation-fragment:2.6.0",
    "androidx.navigation:navigation-fragment-ktx:2.3.5",
    "androidx.navigation:navigation-fragment-ktx:2.4.1",
    "androidx.navigation:navigation-fragment-ktx:2.5.2",
    "androidx.navigation:navigation-fragment-ktx:2.5.3",
    "androidx.navigation:navigation-fragment-ktx:2.6.0",
    "androidx.navigation:navigation-safe-args-gradle-plugin:2.3.1",
    "androidx.navigation:navigation-safe-args-gradle-plugin:2.5.2",
    "androidx.navigation:navigation-safe-args-gradle-plugin:2.5.3",
    "androidx.navigation:navigation-safe-args-gradle-plugin:2.6.0",
    "androidx.navigation:navigation-testing:2.5.3",  # Dependency of architecture-samples
    "androidx.navigation:navigation-ui:2.5.2",
    "androidx.navigation:navigation-ui:2.5.3",
    "androidx.navigation:navigation-ui:2.6.0",
    "androidx.navigation:navigation-ui-ktx:2.3.5",
    "androidx.navigation:navigation-ui-ktx:2.4.1",
    "androidx.navigation:navigation-ui-ktx:2.5.2",
    "androidx.navigation:navigation-ui-ktx:2.5.3",
    "androidx.navigation:navigation-ui-ktx:2.6.0",
    "androidx.palette:palette-ktx:1.0.0",
    "androidx.preference:preference:1.0.0",
    "androidx.preference:preference:1.2.0",
    "androidx.preference:preference:1.2.1",
    "androidx.privacysandbox.activity:activity-client:1.0.0-alpha01",
    "androidx.privacysandbox.activity:activity-core:1.0.0-alpha01",
    "androidx.privacysandbox.activity:activity-provider:1.0.0-alpha01",
    "androidx.privacysandbox.plugins:plugins-privacysandbox-library:1.0.0-alpha01",
    "androidx.privacysandbox.plugins:plugins-privacysandbox-library:1.0.0-alpha02",
    "androidx.privacysandbox.sdkruntime:sdkruntime-client:1.0.0-alpha13",
    "androidx.privacysandbox.sdkruntime:sdkruntime-core:1.0.0-alpha13",
    "androidx.privacysandbox.tools:tools:1.0.0-alpha10",
    "androidx.privacysandbox.tools:tools-apicompiler:1.0.0-alpha10",
    "androidx.privacysandbox.tools:tools-apigenerator:1.0.0-alpha10",
    "androidx.privacysandbox.tools:tools-apipackager:1.0.0-alpha10",
    "androidx.privacysandbox.tools:tools-core:1.0.0-alpha10",
    "androidx.privacysandbox.ui:ui-client:1.0.0-alpha10",
    "androidx.privacysandbox.ui:ui-core:1.0.0-alpha10",
    "androidx.privacysandbox.ui:ui-provider:1.0.0-alpha10",
    "androidx.profileinstaller:profileinstaller:1.3.1",
    "androidx.recyclerview:recyclerview:1.2.1",
    "androidx.recyclerview:recyclerview:1.3.0",
    "androidx.room:room-compiler:2.0.0",
    "androidx.room:room-compiler:2.5.0-rc01",  # Dependency of architecture-samples
    "androidx.room:room-ktx:2.5.0-rc01",  # Dependency of architecture-samples
    "androidx.room:room-runtime:2.0.0",
    "androidx.room:room-testing:2.5.0-rc01",  # Dependency of architecture-samples
    "androidx.savedstate:savedstate-ktx:1.2.1",
    "androidx.slice:slice-builders:1.0.0",
    "androidx.startup:startup-runtime:1.1.1",
    "androidx.test:core:1.3.0",  # TODO: To be removed once dependent tests pass b/273872043
    "androidx.test:core:1.4.0-alpha06",
    "androidx.test:core:1.5.0",
    "androidx.test:core-ktx:1.5.0",  # Dependency of architecture-samples
    "androidx.test.espresso:espresso-contrib:3.5.0",  # Dependency of architecture-samples
    "androidx.test.espresso:espresso-contrib:3.5.1",
    "androidx.test.espresso:espresso-core:3.1.0",
    "androidx.test.espresso:espresso-core:3.2.0",
    "androidx.test.espresso:espresso-core:3.4.0",
    "androidx.test.espresso:espresso-core:3.5.1",
    "androidx.test.espresso:espresso-intents:3.5.0",  # Dependency of architecture-samples
    "androidx.test.espresso.idling:idling-concurrent:3.5.0",  # Dependency of architecture-samples
    "androidx.test.ext:junit:1.1.2",  # TODO: To be removed once dependent tests pass b/273872043
    "androidx.test.ext:junit:1.1.3-alpha02",
    "androidx.test.ext:junit:1.1.5",
    "androidx.test.ext:junit-ktx:1.1.4",  # Dependency of architecture-samples
    "androidx.test:monitor:1.6.1",
    "androidx.test:orchestrator:1.5.0-alpha02",
    "androidx.test:rules:1.1.0",
    "androidx.test:rules:1.3.0",
    "androidx.test:rules:1.4.0-alpha06",
    "androidx.test:runner:1.4.0-alpha06",
    "androidx.test:runner:1.5.2",
    "androidx.test.services:test-services:1.5.0-alpha02",
    "androidx.tracing:tracing-perfetto-handshake:1.0.0-beta02",
    "androidx.tv:tv-foundation:1.0.0-alpha07",
    "androidx.tv:tv-material:1.0.0-alpha07",
    "androidx.tvprovider:tvprovider:1.0.0",
    "androidx.wear.compose:compose-material:1.2.1",
    "androidx.wear.compose:compose-navigation:1.2.1",
    "androidx.wear.compose:compose-ui-tooling:1.2.1",
    "androidx.wear.protolayout:protolayout-expression-pipeline:1.2.0",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.wear.protolayout:protolayout-material:1.2.0",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "androidx.wear.tiles:tiles:1.4.0",
    "androidx.wear.tiles:tiles-material:1.4.0",
    "androidx.wear.tiles:tiles-renderer:1.4.0",
    "androidx.wear.tiles:tiles-tooling:1.4.0",
    "androidx.wear.tiles:tiles-tooling-preview:1.4.0",
    "androidx.wear.watchface:watchface-complications-data-source-ktx:1.2.1",
    "androidx.wear.watchface:watchface-guava:1.1.0",  # Dependency of wearWatchFace
    "androidx.wear.watchface:watchface-guava:1.2.1",
    "androidx.wear:wear:1.2.0",
    "androidx.wear:wear-tooling-preview:1.0.0",
    "com.adobe.marketing.mobile:core:1.5.1",  # Used by SdkIndexIssuesSyncListenerTest
    "com.android.application:com.android.application.gradle.plugin:pom:7.2.0",
    "com.android.application:com.android.application.gradle.plugin:pom:7.4.0",  # Dependency of architecture-samples
    "com.android.application:com.android.application.gradle.plugin:pom:7.4.1",
    "com.android.application:com.android.application.gradle.plugin:pom:7.4.2",
    "com.android.application:com.android.application.gradle.plugin:pom:8.0.2",
    "com.android.application:com.android.application.gradle.plugin:pom:8.1.0",
    "com.android.application:com.android.application.gradle.plugin:pom:8.2.0",
    "com.android.application:com.android.application.gradle.plugin:pom:8.2.2",
    "com.android.application:com.android.application.gradle.plugin:pom:8.3.1",
    "com.android.application:com.android.application.gradle.plugin:pom:8.4.0",
    "com.android.application:com.android.application.gradle.plugin:pom:8.5.0",
    "com.android.application:com.android.application.gradle.plugin:pom:8.6.0",
    "com.android.application:com.android.application.gradle.plugin:pom:8.7.0",
    "com.android.databinding:adapters:4.0.0",
    "com.android.databinding:adapters:4.1.0",
    "com.android.databinding:adapters:4.2.0",
    "com.android.databinding:adapters:7.0.0",
    "com.android.databinding:adapters:7.1.0",
    "com.android.databinding:adapters:7.2.0",
    "com.android.databinding:adapters:7.3.0",
    "com.android.databinding:adapters:7.4.1",
    "com.android.databinding:adapters:8.0.2",
    "com.android.databinding:adapters:8.1.0",
    "com.android.databinding:adapters:8.2.0",
    "com.android.databinding:adapters:8.2.2",
    "com.android.databinding:adapters:8.3.1",
    "com.android.databinding:adapters:8.4.0",
    "com.android.databinding:adapters:8.5.0",
    "com.android.databinding:adapters:8.6.0",
    "com.android.databinding:adapters:8.7.0",
    "com.android.databinding:viewbinding:4.0.0",
    "com.android.databinding:viewbinding:4.1.0",
    "com.android.databinding:viewbinding:4.2.0",
    "com.android.databinding:viewbinding:7.0.0",
    "com.android.databinding:viewbinding:7.1.0",
    "com.android.databinding:viewbinding:7.2.0",
    "com.android.databinding:viewbinding:7.3.0",
    "com.android.databinding:viewbinding:7.4.1",
    "com.android.databinding:viewbinding:8.0.2",
    "com.android.databinding:viewbinding:8.1.0",
    "com.android.databinding:viewbinding:8.2.0",
    "com.android.databinding:viewbinding:8.2.2",
    "com.android.databinding:viewbinding:8.3.1",
    "com.android.databinding:viewbinding:8.4.0",
    "com.android.databinding:viewbinding:8.5.0",
    "com.android.databinding:viewbinding:8.6.0",
    "com.android.databinding:viewbinding:8.7.0",
    "com.android.library:com.android.library.gradle.plugin:pom:7.2.0",
    "com.android.library:com.android.library.gradle.plugin:pom:7.4.0",  # Dependency of architecture-samples
    "com.android.library:com.android.library.gradle.plugin:pom:7.4.1",
    "com.android.library:com.android.library.gradle.plugin:pom:7.4.2",
    "com.android.library:com.android.library.gradle.plugin:pom:8.0.2",
    "com.android.library:com.android.library.gradle.plugin:pom:8.1.0",
    "com.android.library:com.android.library.gradle.plugin:pom:8.2.0",
    "com.android.library:com.android.library.gradle.plugin:pom:8.2.2",
    "com.android.library:com.android.library.gradle.plugin:pom:8.3.1",
    "com.android.library:com.android.library.gradle.plugin:pom:8.4.0",
    "com.android.library:com.android.library.gradle.plugin:pom:8.5.0",
    "com.android.library:com.android.library.gradle.plugin:pom:8.6.0",
    "com.android.library:com.android.library.gradle.plugin:pom:8.7.0",
    "com.android.support:animated-vector-drawable:26.1.0",
    "com.android.support:appcompat-v7:25.4.0",
    "com.android.support:appcompat-v7:26.1.0",
    "com.android.support:cardview-v7:26.1.0",
    "com.android.support.constraint:constraint-layout:1.0.2",
    "com.android.support.constraint:constraint-layout:1.1.0",
    "com.android.support.constraint:constraint-layout:1.1.3",
    "com.android.support.constraint:constraint-layout:2.0.4",
    "com.android.support:leanback-v17:28.0.0",
    "com.android.support:multidex:1.0.1",
    "com.android.support:multidex-instrumentation:1.0.2",
    "com.android.support:preference-v7:28.0.0",
    "com.android.support:recyclerview-v7:27.1.1",
    "com.android.support:support-compat:28.0.0",
    "com.android.support:support-v13:28.0.0",
    "com.android.support:support-v4:24.0.0",
    "com.android.support:support-v4:27.1.1",
    "com.android.support:support-vector-drawable:26.1.0",
    "com.android.support.test.espresso:espresso-contrib:3.0.2",
    "com.android.support.test.espresso:espresso-core:3.0.1",
    "com.android.support.test.espresso:espresso-core:3.0.2",
    "com.android.support.test:orchestrator:1.0.0",
    "com.android.support.test:rules:1.0.2",
    "com.android.support.test.uiautomator:uiautomator-v18:2.1.1",
    "com.android.tools.build:aapt2:jar:linux:3.3.2-5309881",
    "com.android.tools.build:aapt2:jar:linux:3.5.0-5435860",
    "com.android.tools.build:aapt2:jar:linux:4.0.0-6051327",
    "com.android.tools.build:aapt2:jar:linux:4.1.0-6503028",
    "com.android.tools.build:aapt2:jar:linux:4.2.0-7147631",
    "com.android.tools.build:aapt2:jar:linux:7.0.0-7396180",
    "com.android.tools.build:aapt2:jar:linux:7.1.0-7984345",
    "com.android.tools.build:aapt2:jar:linux:7.2.0-7984345",
    "com.android.tools.build:aapt2:jar:linux:7.3.0-8691043",
    "com.android.tools.build:aapt2:jar:linux:7.4.1-8841542",
    "com.android.tools.build:aapt2:jar:linux:7.4.2-8841542",
    "com.android.tools.build:aapt2:jar:linux:8.0.2-9289358",
    "com.android.tools.build:aapt2:jar:linux:8.1.0-10154469",
    "com.android.tools.build:aapt2:jar:linux:8.2.0-10154469",
    "com.android.tools.build:aapt2:jar:linux:8.2.2-10154469",
    "com.android.tools.build:aapt2:jar:linux:8.3.1-10880808",
    "com.android.tools.build:aapt2:jar:linux:8.4.0-11315950",
    "com.android.tools.build:aapt2:jar:linux:8.5.0-11315950",
    "com.android.tools.build:aapt2:jar:linux:8.6.0-11315950",
    "com.android.tools.build:aapt2:jar:linux:8.7.0-12006047",
    "com.android.tools.build:aapt2:jar:osx:7.2.0-7984345",
    "com.android.tools.build:aapt2:jar:osx:7.4.1-8841542",
    "com.android.tools.build:aapt2:jar:osx:8.0.2-9289358",
    "com.android.tools.build:aapt2:jar:osx:8.1.0-10154469",
    "com.android.tools.build:aapt2:jar:osx:8.2.0-10154469",
    "com.android.tools.build:aapt2:jar:osx:8.2.2-10154469",
    "com.android.tools.build:aapt2:jar:osx:8.3.1-10880808",
    "com.android.tools.build:aapt2:jar:osx:8.4.0-11315950",
    "com.android.tools.build:aapt2:jar:osx:8.5.0-11315950",
    "com.android.tools.build:aapt2:jar:osx:8.6.0-11315950",
    "com.android.tools.build:aapt2:jar:osx:8.7.0-12006047",
    "com.android.tools.build:aapt2:jar:windows:7.2.0-7984345",
    "com.android.tools.build:aapt2:jar:windows:7.4.1-8841542",
    "com.android.tools.build:aapt2:jar:windows:8.0.2-9289358",
    "com.android.tools.build:aapt2:jar:windows:8.1.0-10154469",
    "com.android.tools.build:aapt2:jar:windows:8.2.0-10154469",
    "com.android.tools.build:aapt2:jar:windows:8.2.2-10154469",
    "com.android.tools.build:aapt2:jar:windows:8.3.1-10880808",
    "com.android.tools.build:aapt2:jar:windows:8.4.0-11315950",
    "com.android.tools.build:aapt2:jar:windows:8.5.0-11315950",
    "com.android.tools.build:aapt2:jar:windows:8.6.0-11315950",
    "com.android.tools.build:aapt2:jar:windows:8.7.0-12006047",
    "com.android.tools.build:bundletool:1.16.0",
    "com.android.tools.build:gradle:3.0.0",
    "com.android.tools.build:gradle:3.3.2",
    "com.android.tools.build:gradle:3.5.0",
    "com.android.tools.build:gradle:4.0.0",
    "com.android.tools.build:gradle:4.1.0",
    "com.android.tools.build:gradle:4.2.0",
    "com.android.tools.build:gradle:7.0.0",
    "com.android.tools.build:gradle:7.1.0",
    "com.android.tools.build:gradle:7.2.0",
    "com.android.tools.build:gradle:7.3.0",
    "com.android.tools.build:gradle:7.3.1",
    "com.android.tools.build:gradle:7.4.1",
    "com.android.tools.build:gradle:8.1.0",
    "com.android.tools.build:gradle:8.2.0",
    "com.android.tools.build:gradle:8.2.2",
    "com.android.tools.build:gradle:8.3.1",
    "com.android.tools.build:gradle:8.4.0",
    "com.android.tools.build:gradle:8.5.0",
    "com.android.tools.build:gradle:8.6.0",
    "com.android.tools.build:gradle:8.7.0",
    "com.android.tools.build:transform-api:1.5.0",
    "com.android.tools:desugar_jdk_libs:1.0.5",
    "com.android.tools:desugar_jdk_libs:1.1.5",
    "com.android.tools:desugar_jdk_libs_nio:2.0.4",
    "com.android.tools.layoutlib:layoutlib:14.0.9",
    "com.android.tools.layoutlib:layoutlib-resources:14.0.9",
    "com.android.tools.layoutlib:layoutlib-runtime:14.0.9",
    "com.android.tools.lint:lint-checks:26.5.0",
    "com.android.tools.lint:lint-gradle:26.3.2",
    "com.android.tools.lint:lint-gradle:26.5.0",
    "com.android.tools.lint:lint-gradle:27.0.0",
    "com.android.tools.lint:lint-gradle:27.1.0",
    "com.android.tools.lint:lint-gradle:27.2.0",
    "com.android.tools.lint:lint-gradle:30.0.0",
    "com.android.tools.lint:lint-gradle:30.1.0",
    "com.android.tools.lint:lint-gradle:30.2.0",
    "com.android.tools.lint:lint-gradle:30.3.0",
    "com.android.tools.lint:lint-gradle:30.4.1",
    "com.android.tools.lint:lint-gradle:30.4.2",
    "com.android.tools.lint:lint-gradle:31.0.2",
    "com.android.tools.lint:lint-gradle:31.1.0",
    "com.android.tools.lint:lint-gradle:31.2.0",
    "com.android.tools.lint:lint-gradle:31.2.2",
    "com.android.tools.lint:lint-gradle:31.3.1",
    "com.android.tools.lint:lint-gradle:31.4.0",
    "com.android.tools.lint:lint-gradle:31.5.0",
    "com.android.tools.lint:lint-gradle:31.6.0",
    "com.android.tools.lint:lint-gradle:31.7.0",
    "com.android.tools.metalava:metalava:1.0.0-alpha09",
    "com.android.tools.utp:android-device-provider-ddmlib:30.2.0",
    "com.android.tools.utp:android-device-provider-ddmlib:31.1.0",
    "com.android.tools.utp:android-device-provider-ddmlib:jar:30.2.0",
    "com.android.tools.utp:android-device-provider-ddmlib:jar:31.1.0",
    "com.android.tools.utp:android-device-provider-gradle:30.2.0",
    "com.android.tools.utp:android-device-provider-gradle:31.1.0",
    "com.android.tools.utp:android-device-provider-gradle:jar:30.2.0",
    "com.android.tools.utp:android-device-provider-gradle:jar:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-additional-test-output:30.2.0",
    "com.android.tools.utp:android-test-plugin-host-additional-test-output:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-additional-test-output:jar:30.2.0",
    "com.android.tools.utp:android-test-plugin-host-additional-test-output:jar:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-apk-installer:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-apk-installer:jar:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-coverage:30.2.0",
    "com.android.tools.utp:android-test-plugin-host-coverage:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-coverage:jar:30.2.0",
    "com.android.tools.utp:android-test-plugin-host-coverage:jar:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-device-info:30.2.0",
    "com.android.tools.utp:android-test-plugin-host-device-info:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-device-info:jar:30.2.0",
    "com.android.tools.utp:android-test-plugin-host-device-info:jar:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-device-info-proto:30.2.0",
    "com.android.tools.utp:android-test-plugin-host-device-info-proto:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-device-info-proto:jar:30.2.0",
    "com.android.tools.utp:android-test-plugin-host-device-info-proto:jar:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-emulator-control:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-emulator-control:jar:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-logcat:30.2.0",
    "com.android.tools.utp:android-test-plugin-host-logcat:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-logcat:jar:30.2.0",
    "com.android.tools.utp:android-test-plugin-host-logcat:jar:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-retention:30.2.0",
    "com.android.tools.utp:android-test-plugin-host-retention:31.1.0",
    "com.android.tools.utp:android-test-plugin-host-retention:jar:30.2.0",
    "com.android.tools.utp:android-test-plugin-host-retention:jar:31.1.0",
    "com.android.tools.utp:android-test-plugin-result-listener-gradle:30.2.0",
    "com.android.tools.utp:android-test-plugin-result-listener-gradle:31.1.0",
    "com.android.tools.utp:android-test-plugin-result-listener-gradle:jar:30.2.0",
    "com.android.tools.utp:android-test-plugin-result-listener-gradle:jar:31.1.0",
    "com.crashlytics.sdk.android:crashlytics:2.6.8",
    "com.flurry.android:analytics:13.0.0",  # Used by SdkIndexIssuesSyncListenerTest
    "com.github.bumptech.glide:glide:4.11.0",
    "com.google.accompanist:accompanist-appcompat-theme:0.28.0",  # Dependency of architecture-samples
    "com.google.accompanist:accompanist-swiperefresh:0.28.0",  # Dependency of architecture-samples
    "com.google.ai.client.generativeai:generativeai:0.9.0",
    "com.google.android:android:4.1.1.4",
    "com.google.android.gms:play-services-ads:20.6.0",
    "com.google.android.gms:play-services-ads:21.5.0",
    "com.google.android.gms:play-services-ads:9.8.0",
    "com.google.android.gms:play-services-base:15.0.1",
    "com.google.android.gms:play-services-base:17.6.0",
    "com.google.android.gms:play-services-gass:20.0.0",
    "com.google.android.gms:play-services-maps:17.0.1",
    "com.google.android.gms:play-services-maps:18.0.2",
    "com.google.android.gms:play-services-maps:18.1.0",
    "com.google.android.gms:play-services-pay:16.0.3",
    "com.google.android.gms:play-services-pay:16.1.0",
    "com.google.android.gms:play-services-safetynet:10.0.0",  # Used by SdkIndexIssuesSyncListenerTest
    "com.google.android.gms:play-services-wallet:19.1.0",
    "com.google.android.gms:play-services-wearable:17.1.0",
    "com.google.android.gms:play-services-wearable:18.0.0",
    "com.google.android.horologist:horologist-compose-tools:0.6.17",
    "com.google.android.horologist:horologist-tiles:0.6.17",
    "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:com.google.android.libraries.mapsplatform.secrets-gradle-plugin.gradle.plugin:pom:2.0.1",
    "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:2.0.1",
    "com.google.android.material:material:1.1.0",
    "com.google.android.material:material:1.10.0",
    "com.google.android.material:material:1.3.0",
    "com.google.android.material:material:1.4.0",
    "com.google.android.material:material:1.5.0",
    "com.google.android.material:material:1.5.0-alpha04",
    "com.google.android.material:material:1.7.0",
    "com.google.android.material:material:1.8.0",
    "com.google.android.material:material:1.9.0",
    "com.google.android.play:app-update:2.0.0",  # Used by SdkIndexIssuesSyncListenerTest
    "com.google.android.support:wearable:2.9.0",
    "com.google.android.wearable:wearable:2.9.0",
    "com.google.apis:google-api-services-cloudresourcemanager:v1beta1-rev20240128-2.0.0",
    "com.google.apis:google-api-services-oauth2:v2-rev150-1.22.0",
    "com.google.apis:google-api-services-oauth2:v2-rev157-1.25.0",
    "com.google.apis:google-api-services-storage:v1-rev82-1.22.0",
    "com.google.apis:google-api-services-testing:v1-rev20240917-2.0.0",
    "com.google.apis:google-api-services-testing:v1-rev82-1.22.0",
    "com.google.apis:google-api-services-toolresults:v1beta3-rev82-1.22.0",
    "com.google.auth:google-auth-library-credentials:1.24.0",
    "com.google.auth:google-auth-library-oauth2-http:1.24.0",
    "com.google.auto.service:auto-service:1.0-rc2",
    "com.google.auto.value:auto-value:1.4-rc1",
    "com.google.auto.value:auto-value:1.6.2",
    "com.google.auto.value:auto-value-annotations:1.7.4",
    "com.google.code.gson:gson:2.2.4",
    "com.google.code.gson:gson:2.6.2",
    "com.google.crypto.tink:tink:1.3.0-rc2",
    "com.google.dagger:dagger-compiler:2.28.3",
    "com.google.dagger:dagger-compiler:2.52",
    "com.google.dagger:dagger-compiler:2.6",
    "com.google.dagger.hilt.android:com.google.dagger.hilt.android.gradle.plugin:pom:2.44.2",  # Dependency of architecture-samples
    "com.google.dagger:hilt-android:2.40.1",
    "com.google.dagger:hilt-android-gradle-plugin:2.40.1",
    "com.google.dagger:hilt-android-testing:2.44.2",  # Dependency of architecture-samples
    "com.google.dagger:hilt-compiler:2.40.1",
    "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:pom:1.7.10-1.0.6",
    "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:pom:1.8.10-1.0.9",  # Dependency of architecture-samples
    "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:pom:1.8.21-1.0.11",
    "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:pom:1.9.0-1.0.11",
    "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:pom:2.1.0-Beta1-1.0.25",
    "com.google.devtools.ksp:symbol-processing:1.7.10-1.0.6",
    "com.google.devtools.ksp:symbol-processing:1.8.10-1.0.9",
    "com.google.devtools.ksp:symbol-processing:1.8.21-1.0.11",
    "com.google.devtools.ksp:symbol-processing:2.1.0-Beta1-1.0.25",
    "com.google.devtools.ksp:symbol-processing-api:1.7.10-1.0.6",
    "com.google.devtools.ksp:symbol-processing-gradle-plugin:1.7.10-1.0.6",
    "com.google.devtools.ksp:symbol-processing-gradle-plugin:1.8.21-1.0.11",
    "com.google.devtools.ksp:symbol-processing-gradle-plugin:2.1.0-Beta1-1.0.25",
    "com.google.firebase:firebase-common:12.0.1",
    "com.google.firebase:firebase-crashlytics-gradle:2.5.1",
    "com.google.guava:guava:20.0",
    "com.google.guava:guava:28.2-jre",
    "com.google.guava:guava:30.1-android",
    "com.google.guava:guava:31.1-jre",
    "com.google.guava:guava:33.2.1-jre",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "com.google.oauth-client:google-oauth-client-java6:1.34.1",
    "com.google.oboe:oboe:1.6.1",
    "com.google.prefab:cli:jar:all:2.1.0",
    "com.google.protobuf:protobuf-bom:pom:3.17.2",
    "com.google.protobuf:protobuf-bom:pom:3.19.3",
    "com.google.protobuf:protobuf-bom:pom:3.21.8",
    "com.google.protobuf:protobuf-bom:pom:3.22.3",
    "com.google.protobuf:protobuf-java:3.19.3",
    "com.google.protobuf:protobuf-java:3.22.3",
    "com.google.protobuf:protobuf-java-util:3.19.3",
    "com.google.protobuf:protobuf-java-util:3.22.3",
    "com.google.protobuf:protobuf-parent:pom:3.19.3",
    "com.google.protobuf:protobuf-parent:pom:3.22.3",
    "com.google.protobuf:protoc:exe:linux-x86_64:3.19.6",
    "com.google.protobuf:protoc:exe:linux-x86_64:3.22.3",
    "com.google.protobuf:protoc:exe:osx-aarch_64:3.19.6",
    "com.google.protobuf:protoc:exe:osx-aarch_64:3.22.3",
    "com.google.protobuf:protoc:exe:osx-x86_64:3.19.6",
    "com.google.protobuf:protoc:exe:osx-x86_64:3.22.3",
    "com.google.protobuf:protoc:exe:windows-x86_64:3.19.6",
    "com.google.protobuf:protoc:exe:windows-x86_64:3.22.3",
    "com.google.testing.platform:android-device-provider-local:0.0.8-alpha07",
    "com.google.testing.platform:android-device-provider-local:0.0.8-alpha08",
    "com.google.testing.platform:android-device-provider-local:jar:0.0.8-alpha07",
    "com.google.testing.platform:android-driver-instrumentation:0.0.8-alpha07",
    "com.google.testing.platform:android-driver-instrumentation:0.0.8-alpha08",
    "com.google.testing.platform:android-driver-instrumentation:0.0.9-alpha02",
    "com.google.testing.platform:android-test-plugin:0.0.8-alpha07",
    "com.google.testing.platform:android-test-plugin:0.0.8-alpha08",
    "com.google.testing.platform:android-test-plugin:0.0.9-alpha02",
    "com.google.testing.platform:core:0.0.8-alpha07",
    "com.google.testing.platform:core:0.0.8-alpha08",
    "com.google.testing.platform:core:0.0.9-alpha02",
    "com.google.testing.platform:launcher:0.0.8-alpha07",
    "com.google.testing.platform:launcher:0.0.8-alpha08",
    "com.google.truth:truth:0.44",
    "com.google.truth:truth:1.1.2",
    "com.googlecode.jarjar:jarjar:1.3",
    "com.jakewharton.auto.value:auto-value-annotations:1.2-update1",
    "com.jakewharton:butterknife:7.0.1",
    "com.jakewharton:butterknife-gradle-plugin:9.0.0-rc1",
    "com.jakewharton:butterknife-gradle-plugin:9.0.0-rc2",
    "com.jakewharton.timber:timber:5.0.1",  # Dependency of architecture-samples
    "com.linkedin.testbutler:test-butler-app:1.3.1",
    "com.squareup.dagger:dagger-compiler:1.2.2",
    "com.squareup:kotlinpoet:1.12.0",
    "com.squareup.okio:okio:3.4.0",
    "commons-codec:commons-codec:1.9",
    "commons-lang:commons-lang:2.4",
    "io.grpc:grpc-inprocess:1.63.0",
    "io.ktor:ktor-client-content-negotiation-jvm:2.3.2",
    "io.ktor:ktor-client-core-jvm:2.3.2",
    "io.ktor:ktor-client-logging-jvm:2.3.2",
    "io.ktor:ktor-client-okhttp-jvm:2.3.2",
    "io.ktor:ktor-serialization-kotlinx-json-jvm:2.3.2",
    "io.opentracing:opentracing-impl:0.13.0",
    "javax.annotation:javax.annotation-api:1.2",
    "javax.annotation:jsr250-api:1.0",
    "junit:junit:4.13.2",
    "net.java.dev.jna:jna:jna:5.13.0",
    "net.java.dev.jna:jna-platform:5.13.0",
    "org.apache.commons:commons-compress:1.20",
    "org.apache.commons:commons-io:1.3.2",
    "org.apache.commons:commons-lang3:3.13.0",
    "org.apache.commons:commons-text:1.11.0",
    "org.bouncycastle:bcprov-jdk16:1.46",
    "org.brotli:dec:0.1.2",
    "org.bytedeco:ffmpeg-platform:6.0-1.5.9",
    "org.bytedeco:javacpp-platform:1.5.9",
    "org.codehaus.mojo:animal-sniffer-annotations:1.19",
    "org.gradle:gradle-declarative-dsl-core:8.9-20240529002035+0000",  # Version used here should be in the list of verified bootstrap builds
    "org.gradle:gradle-declarative-dsl-tooling-models:8.9-20240529002035+0000",  # Version used here should be in the list of verified bootstrap builds
    "org.jacoco:org.jacoco.agent:0.7.4.201502262128",  # Keep old Jacoco version for testing.
    "org.jacoco:org.jacoco.agent:0.8.12",
    "org.jacoco:org.jacoco.agent:0.8.7",
    "org.jacoco:org.jacoco.agent:0.8.8",
    "org.jacoco:org.jacoco.agent:jar:runtime:0.8.12",
    "org.jacoco:org.jacoco.agent:jar:runtime:0.8.7",
    "org.jacoco:org.jacoco.agent:jar:runtime:0.8.8",
    "org.jacoco:org.jacoco.ant:0.8.12",
    "org.jacoco:org.jacoco.ant:0.8.7",
    "org.jacoco:org.jacoco.ant:0.8.8",
    "org.javassist:javassist:3.26.0-GA",
    "org.jdeferred:jdeferred-android-aar:1.2.2",
    "org.jdeferred:jdeferred-android-aar:1.2.3",
    "org.jetbrains:annotations-java5:jar:24.0.0",
    "org.jetbrains.compose.components:components-resources:1.7.0-beta02",
    "org.jetbrains.compose.components:components-resources-desktop:1.7.0-beta02",
    "org.jetbrains.compose.ui:ui-test-junit4-desktop:1.7.0-beta02",
    "org.jetbrains.dokka:dokka-base:1.4.32",
    "org.jetbrains.dokka:javadoc-plugin:1.4.32",
    "org.jetbrains.jewel:jewel-ide-laf-bridge-242:0.25.0",
    "org.jetbrains.jewel:jewel-int-ui-standalone-242:0.25.0",
    "org.jetbrains.jewel:jewel-markdown-extension-autolink-242:0.25.0",
    "org.jetbrains.jewel:jewel-markdown-extension-gfm-alerts-242:0.25.0",
    "org.jetbrains.jewel:jewel-markdown-ide-laf-bridge-styling-242:0.25.0",
    "org.jetbrains.jewel:jewel-markdown-int-ui-standalone-styling-242:0.25.0",
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:1.7.0",  # Remove it later (b/243935746)
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:1.7.10",
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:1.7.20",
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:1.7.21",
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:1.8.0",
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:1.8.10",
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:1.8.21",
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:1.9.0",
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:1.9.22",
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:1.9.23",
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:1.9.24",
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:2.0.0",  # Compose/Kotlin 2.0.0 templates
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:2.1.0-Beta1",
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:pom:2.1.0-dev-9026",
    "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.1.0-Beta1",
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:1.6.10",
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:1.6.21",
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:1.7.0",
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:1.7.10",
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:1.7.20",
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:1.7.21",
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:1.8.10",
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:1.9.22",
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:1.9.23",
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:2.1.0-Beta1",
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:2.1.0-dev-9026",
    "org.jetbrains.kotlin:jvm-abi-gen:2.0.21",
    "org.jetbrains.kotlin.kapt:org.jetbrains.kotlin.kapt.gradle.plugin:pom:1.8.10",  # Dependency of architecture-samples
    "org.jetbrains.kotlin.kapt:org.jetbrains.kotlin.kapt.gradle.plugin:pom:1.9.22",
    "org.jetbrains.kotlin.kapt:org.jetbrains.kotlin.kapt.gradle.plugin:pom:1.9.23",
    "org.jetbrains.kotlin.kapt:org.jetbrains.kotlin.kapt.gradle.plugin:pom:2.1.0-Beta1",
    "org.jetbrains.kotlin.kapt:org.jetbrains.kotlin.kapt.gradle.plugin:pom:2.1.0-dev-9026",
    "org.jetbrains.kotlin:kotlin-android-extensions:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.41",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.72",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.4.32",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.5.21",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.6.10",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.6.21",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.7.0",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.7.10",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.7.20",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.7.21",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.8.0",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.8.10",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.8.21",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.9.0",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.9.22",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.9.23",
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.9.20",
    "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.9.22",
    "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.9.23",
    "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-bom:pom:1.8.0",
    "org.jetbrains.kotlin:kotlin-bom:pom:1.8.22",
    "org.jetbrains.kotlin:kotlin-build-tools-impl:2.0.0",  # Compose/Kotlin 2.0.0 templates
    "org.jetbrains.kotlin:kotlin-build-tools-impl:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-compiler:1.7.0",
    "org.jetbrains.kotlin:kotlin-compiler:1.7.20",
    "org.jetbrains.kotlin:kotlin-compiler:1.8.10",
    "org.jetbrains.kotlin:kotlin-compiler:1.8.21",
    "org.jetbrains.kotlin:kotlin-compiler:1.9.22",
    "org.jetbrains.kotlin:kotlin-compiler:1.9.23",
    "org.jetbrains.kotlin:kotlin-compiler:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-compiler:2.0.21",
    "org.jetbrains.kotlin:kotlin-compiler-embeddable:1.7.0",
    "org.jetbrains.kotlin:kotlin-compiler-embeddable:1.7.20",
    "org.jetbrains.kotlin:kotlin-compiler-embeddable:1.7.21",
    "org.jetbrains.kotlin:kotlin-compiler-embeddable:1.8.10",
    "org.jetbrains.kotlin:kotlin-compose-compiler-plugin-embeddable:2.0.0",  # Compose/Kotlin 2.0.0 templates
    "org.jetbrains.kotlin:kotlin-compose-compiler-plugin-embeddable:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-compose-compiler-plugin:2.0.21",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.41",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.32",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.21",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.21",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.23",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0-dev-9026",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:jar:gradle70:1.7.0",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:jar:gradle70:1.7.10",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:jar:gradle70:1.7.20",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:jar:gradle70:1.7.21",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:jar:gradle71:1.7.20",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:jar:gradle71:1.7.21",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:jar:gradle76:1.8.0",
    "org.jetbrains.kotlin:kotlin-gradle-plugin:jar:gradle76:1.8.10",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.0",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.21",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.10",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.21",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.9.22",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.9.23",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:jar:gradle70:1.7.0",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:jar:gradle70:1.7.10",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:jar:gradle70:1.7.20",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:jar:gradle70:1.7.21",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:jar:gradle71:1.7.20",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:jar:gradle71:1.7.21",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:jar:gradle76:1.8.0",
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:jar:gradle76:1.8.10",
    "org.jetbrains.kotlin:kotlin-klib-commonizer-embeddable:1.8.21",
    "org.jetbrains.kotlin:kotlin-klib-commonizer-embeddable:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-native-prebuilt:tar.gz:linux-x86_64:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-native-prebuilt:tar.gz:macos-aarch64:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-native-prebuilt:tar.gz:macos-x86_64:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-native-prebuilt:zip:windows-x86_64:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-parcelize-compiler:1.7.20",
    "org.jetbrains.kotlin:kotlin-parcelize-runtime:1.7.20",
    "org.jetbrains.kotlin:kotlin-reflect:1.4.31",
    "org.jetbrains.kotlin:kotlin-reflect:1.5.21",
    "org.jetbrains.kotlin:kotlin-reflect:1.6.10",
    "org.jetbrains.kotlin:kotlin-reflect:1.6.21",
    "org.jetbrains.kotlin:kotlin-reflect:1.7.0",
    "org.jetbrains.kotlin:kotlin-reflect:1.7.20",
    "org.jetbrains.kotlin:kotlin-reflect:1.7.21",
    "org.jetbrains.kotlin:kotlin-reflect:1.8.0",
    "org.jetbrains.kotlin:kotlin-reflect:1.8.10",
    "org.jetbrains.kotlin:kotlin-reflect:1.8.20",
    "org.jetbrains.kotlin:kotlin-reflect:1.8.21",
    "org.jetbrains.kotlin:kotlin-reflect:1.9.0",
    "org.jetbrains.kotlin:kotlin-reflect:1.9.10",
    "org.jetbrains.kotlin:kotlin-reflect:1.9.20",
    "org.jetbrains.kotlin:kotlin-reflect:1.9.22",
    "org.jetbrains.kotlin:kotlin-reflect:1.9.23",
    "org.jetbrains.kotlin:kotlin-reflect:1.9.24",
    "org.jetbrains.kotlin:kotlin-reflect:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-script-runtime:1.5.21",
    "org.jetbrains.kotlin:kotlin-script-runtime:1.6.10",
    "org.jetbrains.kotlin:kotlin-script-runtime:1.6.21",
    "org.jetbrains.kotlin:kotlin-script-runtime:1.7.0",
    "org.jetbrains.kotlin:kotlin-script-runtime:1.7.20",
    "org.jetbrains.kotlin:kotlin-script-runtime:1.7.21",
    "org.jetbrains.kotlin:kotlin-script-runtime:1.8.0",
    "org.jetbrains.kotlin:kotlin-script-runtime:1.8.10",
    "org.jetbrains.kotlin:kotlin-script-runtime:1.8.21",
    "org.jetbrains.kotlin:kotlin-script-runtime:1.9.0",
    "org.jetbrains.kotlin:kotlin-script-runtime:1.9.24",
    "org.jetbrains.kotlin:kotlin-script-runtime:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-stdlib-common:1.9.22",
    "org.jetbrains.kotlin:kotlin-stdlib-common:1.9.23",
    "org.jetbrains.kotlin:kotlin-stdlib-common:1.9.24",
    "org.jetbrains.kotlin:kotlin-stdlib-common:2.0.0",  # Compose/Kotlin 2.0.0 templates
    "org.jetbrains.kotlin:kotlin-stdlib-common:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-stdlib-common:2.1.0-dev-9026",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.4.32",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.31",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.21",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.0",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.10",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.20",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.0",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.24",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.0",  # Compose/Kotlin 2.0.0 templates
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.0-Beta1",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.0-dev-9026",
    "org.jetbrains.kotlin:kotlin-stdlib-js:1.7.0",
    "org.jetbrains.kotlin:kotlin-test:1.9.24",
    "org.jetbrains.kotlin:kotlin-test-junit:1.7.10",
    "org.jetbrains.kotlin:kotlin-test-junit:1.9.24",
    "org.jetbrains.kotlin:kotlin-test-junit:2.1.0-Beta1",
    "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin:pom:1.8.21",
    "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:pom:2.0.0",  # Compose/Kotlin 2.0.0 templates
    "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:pom:2.1.0-Beta1",
    "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:pom:2.1.0-dev-9026",
    "org.jetbrains.kotlin.plugin.parcelize:org.jetbrains.kotlin.plugin.parcelize.gradle.plugin:pom:2.1.0-Beta1",  # Used by com.android.tools.idea.benchmarks.tests.JetNewsBenchmarkTest
    "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.0.1",
    "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.6",
    "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.1",
    "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4",
    "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.1",
    "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.6",
    "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.1",
    "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.3",
    "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4",
    "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3",
    "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:1.3.6",
    "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.7.3",
    "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:1.7.3",
    "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.3",
    "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.0-RC2",
    "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.1",  # Needed for TemplateTest#testNewComposeWearActivityWithTileAndComplication
    "org.jetbrains.kotlinx:kotlinx-serialization-core:1.6.0",
    "org.jetbrains.kotlinx:kotlinx-serialization-core:1.6.3",
    "org.jetbrains.skiko:skiko:0.7.7",
    "org.jetbrains.skiko:skiko-awt:0.7.7",
    "org.jetbrains.skiko:skiko-awt:0.8.12",
    "org.jetbrains.skiko:skiko-awt-runtime-linux-x64:0.7.16",
    "org.jetbrains.skiko:skiko-awt-runtime-linux-x64:0.8.12",
    "org.jetbrains.skiko:skiko-awt-runtime-macos-arm64:0.7.16",
    "org.jetbrains.skiko:skiko-awt-runtime-macos-arm64:0.8.12",
    "org.jetbrains.skiko:skiko-awt-runtime-macos-x64:0.7.16",
    "org.jetbrains.skiko:skiko-awt-runtime-macos-x64:0.8.12",
    "org.jetbrains.skiko:skiko-awt-runtime-windows-x64:0.7.16",
    "org.jetbrains.skiko:skiko-awt-runtime-windows-x64:0.8.12",
    "org.junit:junit-bom:pom:5.10.0",
    "org.junit:junit-bom:pom:5.9.2",
    "org.junit:junit-bom:pom:5.9.3",
    "org.junit.platform:junit-platform-engine:1.10.1",
    "org.junit.platform:junit-platform-launcher:1.10.1",
    "org.mockito.kotlin:mockito-kotlin:5.4.0",
    "org.robolectric:android-all-instrumented:7.0.0_r1-robolectric-r1-i4",  # Runtime for Android N
    "org.robolectric:android-all-instrumented:9-robolectric-4913185-2-i4",  # Runtime for Android P
    "org.robolectric:robolectric:4.8.2",
    "org.tensorflow:tensorflow-lite-metadata:0.1.0",
    "org.tensorflow:tensorflow-lite-support:0.1.0",
    "org.threeten:threetenbp:1.3.3",
    "org.tukaani:xz:1.9",
    "org.xerial:sqlite-jdbc:3.21.0.1",
    "org.xerial:sqlite-jdbc:3.34.0",
] + [
    # Source JARs
    # keep sorted
    "androidx.arch.core:core-common:jar:sources:2.2.0",
    "androidx.collection:collection-jvm:jar:sources:1.4.0",
    "androidx.lifecycle:lifecycle-common-jvm:jar:sources:2.8.4",
    "androidx.lifecycle:lifecycle-runtime-desktop:jar:sources:2.8.4",
    "androidx.lifecycle:lifecycle-viewmodel-desktop:jar:sources:2.8.4",
    "com.squareup.okhttp3:okhttp:jar:sources:4.12.0",
    "com.squareup.okio:okio-jvm:jar:sources:3.6.0",
    "io.grpc:grpc-all:jar:sources:1.57.0",
    "io.grpc:grpc-api:jar:sources:1.57.0",
    "io.grpc:grpc-auth:jar:sources:1.57.0",
    "io.grpc:grpc-context:jar:sources:1.57.0",
    "io.grpc:grpc-core:jar:sources:1.57.0",
    "io.grpc:grpc-netty:jar:sources:1.57.0",
    "io.grpc:grpc-netty-shaded:jar:sources:1.57.0",
    "io.grpc:grpc-okhttp:jar:sources:1.57.0",
    "io.grpc:grpc-protobuf:jar:sources:1.57.0",
    "io.grpc:grpc-protobuf-lite:jar:sources:1.57.0",
    "io.grpc:grpc-stub:jar:sources:1.57.0",
    "org.brotli:dec:jar:sources:0.1.2",
    "org.commonmark:commonmark:jar:sources:0.22.0",
    "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose-desktop:jar:sources:2.8.1",
    "org.jetbrains.compose.animation:animation-core-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.animation:animation-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.components:components-resources:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.components:components-resources-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.foundation:foundation-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.foundation:foundation-layout-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.runtime:runtime-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.runtime:runtime-saveable-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.ui:ui-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.ui:ui-geometry-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.ui:ui-graphics-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.ui:ui-test-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.ui:ui-test-junit4-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.ui:ui-text-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.ui:ui-unit-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.compose.ui:ui-util-desktop:jar:sources:1.7.0-beta02",
    "org.jetbrains.jewel:jewel-foundation-242:jar:sources:0.25.0",
    "org.jetbrains.jewel:jewel-ide-laf-bridge-242:jar:sources:0.25.0",
    "org.jetbrains.jewel:jewel-int-ui-standalone-242:jar:sources:0.25.0",
    "org.jetbrains.jewel:jewel-markdown-core-242:jar:sources:0.25.0",
    "org.jetbrains.jewel:jewel-markdown-extension-autolink-242:jar:sources:0.25.0",
    "org.jetbrains.jewel:jewel-markdown-extension-gfm-alerts-242:jar:sources:0.25.0",
    "org.jetbrains.jewel:jewel-markdown-ide-laf-bridge-styling-242:jar:sources:0.25.0",
    "org.jetbrains.jewel:jewel-markdown-int-ui-standalone-styling-242:jar:sources:0.25.0",
    "org.jetbrains.jewel:jewel-ui-242:jar:sources:0.25.0",
    "org.jetbrains.kotlin:kotlin-stdlib:jar:sources:1.9.22",
    "org.jetbrains.kotlin:kotlin-stdlib:jar:sources:1.9.23",
    "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:jar:sources:1.6.4",
    "org.jetbrains.kotlinx:kotlinx-coroutines-test-jvm:jar:sources:1.6.4",
    "org.jetbrains.kotlinx:kotlinx-coroutines-test-jvm:jar:sources:1.8.0-RC2",
    "org.jetbrains.skiko:skiko-awt:jar:sources:0.8.12",
    "org.jetbrains.skiko:skiko-awt-runtime-linux-x64:jar:sources:0.8.12",
    "org.jetbrains.skiko:skiko-awt-runtime-macos-arm64:jar:sources:0.8.12",
    "org.jetbrains.skiko:skiko-awt-runtime-macos-x64:jar:sources:0.8.12",
    "org.jetbrains.skiko:skiko-awt-runtime-windows-x64:jar:sources:0.8.12",
    "org.robolectric:plugins-maven-dependency-resolver:jar:sources:4.8.2",
    "org.robolectric:robolectric:jar:sources:4.8.2",
]

REMOTE_REPOS = {
    "Maven Central": "https://repo1.maven.org/maven2/",
    "JCenter": "https://jcenter.bintray.com/",
    "Google": "https://maven.google.com/",
    "Gradle Libs": "https://repo.gradle.org/gradle/libs-releases/",
    "GradlePlugins": "https://plugins.gradle.org/m2",
    "Kotlin dev": "https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev/",
    "Gradle Snapshots": "https://repo.gradle.org/gradle/libs-snapshots/",
    "IntelliJ Third-Party deps": "https://cache-redirector.jetbrains.com/intellij-dependencies",
    "Compose": "https://maven.pkg.jetbrains.space/public/p/compose/dev/",
    "Jewel": "https://packages.jetbrains.team/maven/p/kpm/public/",
}
