load("//tools/base/intellij-bazel:intellij.bzl", "intellij_platform_setting")

intellij_platform_setting(
    name = "intellij_platform",
    build_setting_default = "studio-sdk",
    visibility = ["//visibility:public"],
)
