load(
    ":release_version.bzl",
    _RELEASE_BASE_VERSION = "BASE_VERSION",
    _RELEASE_BUILD_VERSION = "BUILD_VERSION",
    _RELEASE_COMMANDLINE_TOOLS_VERSION = "COMMANDLINE_TOOLS_VERSION",
)

RELEASE_BASE_VERSION = _RELEASE_BASE_VERSION
DEV_BASE_VERSION = RELEASE_BASE_VERSION.split("-")[0] + "-dev"
BASE_VERSION = select({
    "//tools/base/bazel:release": RELEASE_BASE_VERSION,
    "//conditions:default": DEV_BASE_VERSION,
})

RELEASE_BUILD_VERSION = _RELEASE_BUILD_VERSION
DEV_BUILD_VERSION = RELEASE_BUILD_VERSION.split("-")[0] + "-dev"
BUILD_VERSION = select({
    "//tools/base/bazel:release": RELEASE_BUILD_VERSION,
    "//conditions:default": DEV_BUILD_VERSION,
})

RELEASE_COMMANDLINE_TOOLS_VERSION = _RELEASE_COMMANDLINE_TOOLS_VERSION
DEV_COMMANDLINE_TOOLS_VERSION = RELEASE_COMMANDLINE_TOOLS_VERSION.split("-")[0] + "-dev"
COMMANDLINE_TOOLS_VERSION = select({
    "//tools/base/bazel:release": RELEASE_COMMANDLINE_TOOLS_VERSION,
    "//conditions:default": DEV_COMMANDLINE_TOOLS_VERSION,
})
