load("//tools/base/bazel:utils.bzl", "merged_zip")

merged_zip(
    name = "preview_screenshot_maven_repo",
    srcs = [
        "//tools/base/preview/screenshot/junit-engine:maven_repo.zip",
        "//tools/base/preview/screenshot/preview-screenshot-gradle-plugin:preview_screenshot-gradle-plugin.zip",
    ],
)
